version: "3.9"

services:
  fe:
    container_name: frontend-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production
    networks:
      - dev-net

networks:
  dev-net:
    external: true